/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsKlijent;

import controller.ClientController;
import domain.Klijent;
import domain.Termin;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Jela
 */
public class InfoKlijentaForm extends javax.swing.JDialog
{

    private Klijent k;

    public InfoKlijentaForm(JDialog parent, boolean modal, Klijent k) throws Exception
    {
        super(parent, modal);
        initComponents();
        this.k = k;
        setLocationRelativeTo(null);
	setTitle("Informacije o klijentu");
        cmbGrad.getModel().setSelectedItem(k.getGradFirme());
        txtImeVlasnika.setText(k.getImeVlasnika());
        txtIndustrija.setText(k.getIndustrija());
        txtKontakt.setText(k.getKontakt());
        txtNazivFirme.setText(k.getNazivFirme());
        txtIndustrija.setEditable(false);
	txtNazivFirme.setEditable(false);
	popuniTermine();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnZatvori = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        txtNazivFirme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIndustrija = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtImeVlasnika = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKontakt = new javax.swing.JTextField();
        cmbGrad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbTermini = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnZatvori.setBackground(new java.awt.Color(255, 255, 255));
        btnZatvori.setForeground(new java.awt.Color(0, 102, 255));
        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnZatvoriActionPerformed(evt);
            }
        });

        btnObrisi.setBackground(new java.awt.Color(255, 255, 255));
        btnObrisi.setForeground(new java.awt.Color(0, 102, 255));
        btnObrisi.setText("Obrisi klijenta");
        btnObrisi.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzmeni.setBackground(new java.awt.Color(51, 153, 255));
        btnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("Izmeni klijenta");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Grad:");

        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Industrija:");

        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Ime vlasnika:");

        txtIndustrija.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIndustrijaActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Kontakt:");

        txtImeVlasnika.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtImeVlasnikaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Naziv firme:");

        txtKontakt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtKontaktActionPerformed(evt);
            }
        });

        cmbGrad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beograd", "Nis", "Novi Sad", "Subotica", "Pirot" }));

        jLabel1.setText("Termini klijenta");

        cmbTermini.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNazivFirme)
                            .addComponent(txtIndustrija)
                            .addComponent(txtImeVlasnika)
                            .addComponent(txtKontakt)
                            .addComponent(cmbGrad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTermini, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnIzmeni, btnObrisi, btnZatvori});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivFirme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIndustrija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImeVlasnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTermini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZatvori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

	int deleteYesNo = JOptionPane.showConfirmDialog(this,
		"Da li ste sigurni da zelite da obrisete ovog klijenta?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

	if (deleteYesNo == JOptionPane.NO_OPTION)
	{
            return;
        }

	if (deleteYesNo == JOptionPane.YES_OPTION)
	{
            try {
                ClientController.getInstance().deleteKlijent(k);
		PretragaKlijentaForm pkf = (PretragaKlijentaForm) getParent();
		pkf.refreshTable();
		pkf.popuniKlijente();
                JOptionPane.showMessageDialog(this, "Uspesno obrisan klijent.");
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ne mozete da obrisete ovog klijenta jer "
                        + "je imao konsultacije!");
            }
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        if (txtNazivFirme.getText().isEmpty() || txtIndustrija.getText().isEmpty()
                || txtImeVlasnika.getText().isEmpty()
                || txtKontakt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
            return;
        }

        String grad = (String) cmbGrad.getSelectedItem();
        String imeVlasnika = txtImeVlasnika.getText();
        String kontakt = txtKontakt.getText();

        k.setGradFirme(grad);
        k.setImeVlasnika(imeVlasnika);
        k.setKontakt(kontakt);

        try {
            ClientController.getInstance().updateKlijent(k);
	    PretragaKlijentaForm pkf = (PretragaKlijentaForm) getParent();
	    pkf.refreshTable();
	    pkf.popuniKlijente();
	    JOptionPane.showMessageDialog(this,
		    "Uspesno izmenjeni podaci klijenta!");
            this.dispose();
        } catch (Exception ex) {
	    Logger.getLogger(InfoKlijentaForm.class.getName()).log(Level.SEVERE,
		    null, ex);
        }

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void txtIndustrijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndustrijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndustrijaActionPerformed

    private void txtImeVlasnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeVlasnikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeVlasnikaActionPerformed

    private void txtKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKontaktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKontaktActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JComboBox<String> cmbGrad;
    private javax.swing.JComboBox cmbTermini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtImeVlasnika;
    private javax.swing.JTextField txtIndustrija;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtNazivFirme;
    // End of variables declaration//GEN-END:variables

    private void popuniTermine() throws Exception
    {
	/*ArrayList<Termin> termini = ClientController.getInstance().getAllTermin();
	

	
	ArrayList<Termin> terminiKlijenta = new ArrayList<>();

	for (Termin t : termini)
	{
	    if (t.getKlijent().getKlijentID().equals(k.getKlijentID()))
	    {
		terminiKlijenta.add(t);
	    }
	}*/

	ArrayList<Termin> terminiKlijenta = ClientController.getInstance().getAllTermin(
		k);
	cmbTermini.removeAllItems();

	for (Termin termin : terminiKlijenta)
	{
	    cmbTermini.addItem(termin);
	}
    }

}
