/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsKlijent;

import controller.ClientController;
import domain.Klijent;
import forms.MainForm;
import javax.swing.JOptionPane;

/**
 *
 * @author Jela
 */
public class NoviKlijentForm extends javax.swing.JDialog {

    public NoviKlijentForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
	setTitle("Dodavanje novog klijenta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        txtNazivFirme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnOtkazi = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIndustrija = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtImeVlasnika = new javax.swing.JTextField();
        txtKontakt = new javax.swing.JTextField();
        cmbGrad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 255));

        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Naziv firme:");

        txtNazivFirme.setText("Hooloovoo");

        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Grad:");

        btnOtkazi.setBackground(new java.awt.Color(255, 255, 255));
        btnOtkazi.setForeground(new java.awt.Color(0, 102, 255));
        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnDodaj.setBackground(new java.awt.Color(51, 153, 255));
        btnDodaj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDodaj.setForeground(new java.awt.Color(255, 255, 255));
        btnDodaj.setText("Dodaj klijenta");
        btnDodaj.setBorderPainted(false);
        btnDodaj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDodajActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Industrija:");

        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Ime vlasnika:");

        txtIndustrija.setText("IT");
        txtIndustrija.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIndustrijaActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Kontakt:");

        txtImeVlasnika.setText("Predrag Spasojević");
        txtImeVlasnika.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtImeVlasnikaActionPerformed(evt);
            }
        });

        txtKontakt.setText("0112832983");
        txtKontakt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtKontaktActionPerformed(evt);
            }
        });

        cmbGrad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beograd", "Nis", "Novi Sad", "Subotica", "Pirot", "Vranje" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNazivFirme, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(txtIndustrija)
                            .addComponent(txtImeVlasnika)
                            .addComponent(txtKontakt)
                            .addComponent(cmbGrad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivFirme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIndustrija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImeVlasnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnOtkazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try {
            if (txtNazivFirme.getText().isEmpty() || txtIndustrija.getText().isEmpty()
                    || txtImeVlasnika.getText().isEmpty()
                    || txtKontakt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
                return;
            }

            String nazivFirme = txtNazivFirme.getText();
            String grad = (String) cmbGrad.getSelectedItem();
            String industrija = txtIndustrija.getText();
            String imeVlasnika = txtImeVlasnika.getText();
            String kontakt = txtKontakt.getText();

            Klijent k = new Klijent(null, nazivFirme, grad, industrija, imeVlasnika, kontakt);

            ClientController.getInstance().addKlijent(k);
            MainForm mf = (MainForm) getParent();
            mf.popuniKlijente();
	    JOptionPane.showMessageDialog(this, "Uspesno dodat novi klijent!");
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void txtIndustrijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndustrijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndustrijaActionPerformed

    private void txtImeVlasnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeVlasnikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeVlasnikaActionPerformed

    private void txtKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKontaktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKontaktActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JComboBox<String> cmbGrad;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtImeVlasnika;
    private javax.swing.JTextField txtIndustrija;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtNazivFirme;
    // End of variables declaration//GEN-END:variables
}
